'use client'

import { useState } from 'react'
import Image from 'next/image'
import { ArrowDown, ArrowRight, ArrowUpRight, Bookmark, Code2, Flame, ImageIcon, Layers3, Megaphone, Search, Sparkles, Trash2 } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from '@/components/ui/sheet'
import { Input } from '@/components/ui/input'
import { ToggleGroup, ToggleGroupItem } from '@/components/ui/toggle-group'
import { categories, recipes, type PromptResult, type Recipe } from '@/lib/prompt-engine'

export const categoryIcons = { visual: ImageIcon, code: Code2, content: Megaphone }
function RecipeArt({ art }: { art: string }) {
  if (art === 'cyberpunk') return <Image src="/images/cyberpunk.png" alt="Neon-lit city at night with a lone figure in the rain" fill sizes="(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 300px" className="object-cover" />
  if (art === 'product') return <Image src="/images/product.png" alt="Botanical serum bottle on travertine in warm morning light" fill sizes="(max-width: 640px) 50vw, 300px" className="object-cover" />
  if (art === 'saas') return <div className="mini-site" aria-hidden="true"><div className="mini-site-nav"><span>◈ orbit</span><span>Product &nbsp; Resources <b>Get started ↗</b></span></div><div className="mini-site-content"><div><span className="mini-eyebrow">LESS BUSY. MORE BRILLIANT.</span><strong>Your best work.<br />Without the busywork.</strong><span className="mini-site-cta">Make space for more ↗</span></div><div className="orbit-art"><Layers3 /><div /></div></div></div>
  if (art === 'launch') return <div className="launch-art" aria-hidden="true"><div className="launch-lines" /><span className="launch-kicker">INTRODUCING YOUR NEXT BIG THING</span><strong>Make some<br /><em>noise.</em><ArrowUpRight /></strong><span className="launch-small">Great products deserve a great entrance.</span></div>
  return <div className="mini-dashboard" aria-hidden="true"><div className="mini-dash-sidebar"><Layers3 /><span /><span /><span /><span /></div><div className="mini-dash-main"><div className="mini-dash-title">Overview <span>Last 30 days⌄</span></div><div className="mini-dash-metrics"><div><span>Total revenue</span><strong>$48,295</strong><small>↗ 12.8%</small></div><div><span>Active users</span><strong>2,420</strong><small>↗ 8.2%</small></div><div><span>Conversion</span><strong>4.28%</strong><small>↗ 2.1%</small></div></div><div className="mini-chart">{[25, 35, 29, 44, 36, 47, 42, 58, 50, 67, 55, 72, 68, 84, 78, 93, 87, 100].map((height, i) => <i key={i} style={{ height: `${height}%` }} />)}</div></div></div>
}
function RecipeCard({ recipe, onSelect }: { recipe: Recipe; onSelect: (recipe: Recipe) => void }) {
  const Icon = categoryIcons[recipe.category]
  return <button className="recipe-card group" onClick={() => onSelect(recipe)}><div className={`recipe-art recipe-art-${recipe.art}`}><RecipeArt art={recipe.art} /><Badge variant="secondary"><Icon data-icon="inline-start" />{recipe.category === 'code' ? 'Development' : recipe.category === 'visual' ? 'Visual art' : 'Marketing'}</Badge><span className="recipe-hover"><ArrowUpRight className="size-4" /></span></div><div className="recipe-info"><h3>{recipe.title}</h3><p>{recipe.description}</p><div><span>{recipe.tag}</span><ArrowUpRight className="size-3.5" /></div></div></button>
}
export function TrendingRecipes({ onSelect, onBrowse }: { onSelect: (recipe: Recipe) => void; onBrowse: () => void }) {
  return <section className="discovery" aria-labelledby="recipes-title"><div className="discovery-heading"><div><h2 id="recipes-title"><Flame className="size-4" />A little inspiration goes a long way.</h2><p>Skip the blank canvas. Start with a recipe, make it yours.</p></div><Button variant="ghost" size="sm" onClick={onBrowse}>Explore all templates<ArrowRight data-icon="inline-end" /></Button></div><div className="recipe-grid">{recipes.slice(0, 4).map(recipe => <RecipeCard key={recipe.id} recipe={recipe} onSelect={onSelect} />)}</div></section>
}
export function TemplateLibrary({ open, onOpenChange, onSelect }: { open: boolean; onOpenChange: (open: boolean) => void; onSelect: (recipe: Recipe) => void }) {
  const [query, setQuery] = useState('')
  const [filter, setFilter] = useState('all')
  const filtered = recipes.filter(recipe => (filter === 'all' || recipe.category === filter) && `${recipe.title} ${recipe.description} ${recipe.engine}`.toLowerCase().includes(query.toLowerCase()))
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="template-dialog sm:max-w-4xl p-6"><DialogHeader><DialogTitle><span className="flex items-center gap-2"><Sparkles className="size-5 text-primary" />The template collection</span></DialogTitle><DialogDescription>Expertly structured starting points. All free to make your own.</DialogDescription></DialogHeader><div className="search-field"><Search className="size-4" /><Input aria-label="Search templates" placeholder="Search for your next big idea…" value={query} onChange={e => setQuery(e.target.value)} /></div><ToggleGroup value={[filter]} onValueChange={value => value.length && setFilter(value[0])} className="library-filters flex-wrap" size="sm"><ToggleGroupItem value="all">All templates</ToggleGroupItem>{Object.entries(categories).map(([key, value]) => <ToggleGroupItem key={key} value={key}>{value.label}</ToggleGroupItem>)}</ToggleGroup><div className="library-grid max-h-[55vh] overflow-y-auto">{filtered.length ? filtered.map(recipe => <RecipeCard key={recipe.id} recipe={recipe} onSelect={recipe => { onSelect(recipe); onOpenChange(false) }} />) : <p className="col-span-full py-12 text-center text-muted-foreground">No templates match your search. Try another idea.</p>}</div></DialogContent></Dialog>
}
export function HistoryDrawer({ open, onOpenChange, history, favorites, onRestore, onDelete }: { open: boolean; onOpenChange: (open: boolean) => void; history: PromptResult[]; favorites: string[]; onRestore: (result: PromptResult) => void; onDelete: (id: string) => void }) {
  const [filter, setFilter] = useState('all')
  const shown = history.filter(item => filter !== 'favorites' || favorites.includes(item.id))
  return <Sheet open={open} onOpenChange={onOpenChange}><SheetContent className="history-sheet sm:max-w-md"><SheetHeader className="p-6"><SheetTitle>Your creative collection</SheetTitle><SheetDescription>Prompts from this session. Export the keepers before you leave.</SheetDescription></SheetHeader><div className="px-6"><ToggleGroup value={[filter]} onValueChange={value => value.length && setFilter(value[0])} size="sm"><ToggleGroupItem value="all">History ({history.length})</ToggleGroupItem><ToggleGroupItem value="favorites"><Bookmark />Favorites ({favorites.length})</ToggleGroupItem></ToggleGroup></div><div className="flex flex-col gap-3 overflow-y-auto p-6">{shown.length ? shown.map(item => <article className="history-item" key={item.id}><div className="flex items-center justify-between"><Badge variant="outline">{item.settings.engine}</Badge>{favorites.includes(item.id) && <Bookmark className="size-3.5 fill-current text-primary" />}</div><h3>{item.settings.idea}</h3><p>{item.createdAt} · v{item.variant + 1}</p><div className="flex items-center justify-between"><Button variant="secondary" size="sm" onClick={() => { onRestore(item); onOpenChange(false) }}>Open prompt<ArrowRight data-icon="inline-end" /></Button><Button variant="ghost" size="icon-sm" aria-label={`Delete ${item.settings.idea}`} onClick={() => onDelete(item.id)}><Trash2 /></Button></div></article>) : <div className="history-empty"><Bookmark className="size-9" /><h3>{filter === 'favorites' ? 'Keep your favorite ideas close.' : 'Your next great idea belongs here.'}</h3><p>{filter === 'favorites' ? 'Use the bookmark button on any generated prompt to save it here.' : 'Generate a prompt and it will appear in your session history.'}</p><ArrowDown className="size-4" /></div>}</div></SheetContent></Sheet>
}
